[package]
name = "egoc-auction"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
egoc-field  = { path = "../egoc-field" }
egoc-sl2    = { path = "../egoc-sl2" }
egoc-linalg = { path = "../egoc-linalg" }
egoc-code   = { path = "../egoc-code" }
egoc-proof  = { path = "../egoc-proof" }
rand.workspace = true

[[bin]]
name = "egoc-auction"
path = "src/main.rs"
